name: snowpark-de-ml
channels:
  - https://repo.anaconda.com/pkgs/snowflake
dependencies:
  - python=3.8
  - snowflake-snowpark-python=1.3.0
  - pandas=1.4.4
  - notebook=6.5.2
  - scikit-learn=1.2.1
  - cachetools=4.2.2
  - boto3
  - pip
  - pip:
    - streamlit==1.21.0
 
